### PR TITLE
Put archer password in a file

### PR DESCRIPTION
**Pull request by wintun12**
- modify the script so that it's not required to provide the password as direct input. 
- also modify not to include the undetermined fastq files in the process

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/archer_api_upload/4)

### CODE REVIEW

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_api_upload/4)* status: all files reviewed, 2 unresolved discussions (waiting on @wintun12)

___
*[`main.sh` line 10 at r1](https://reviewable.io/reviews/moka-guys/archer_api_upload/4#-O6_Tdlk9wZVDVD2lqXO:-O6_Tdlk9wZVDVD2lqXP:b-a0ocao) ([raw file](https://github.com/moka-guys/archer_api_upload/blob/ddd7132ef9a671d86ef41e9e99541738a0bf748f/main.sh#L10)):*
> ```Shell
> 
> # get the archer password
> pw=$(cat $pw_file)
> ```

Does this print the password in the log file?
___
*[`main.sh` line 62 at r2](https://reviewable.io/reviews/moka-guys/archer_api_upload/4#-O7in5sV8iBVAgJaQ6vo:-O7in5sW7OnRwRgYnDUI:b-z1vnez) ([raw file](https://github.com/moka-guys/archer_api_upload/blob/374f78ac49a069f2524b007d6fe894791696b6be/main.sh#L62)):*
> ```Shell
>   -H "Authorization: Basic $pw" \
>   -d "$sample_list"
> ```

assuming the proxy command would go here

**Review by wintun12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_api_upload/4)* status: all files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[`main.sh` line 10 at r1](https://reviewable.io/reviews/moka-guys/archer_api_upload/4#-O6_Tdlk9wZVDVD2lqXO:-O7ipSZ85sOWijMM4BK4:b9y8695) ([raw file](https://github.com/moka-guys/archer_api_upload/blob/ddd7132ef9a671d86ef41e9e99541738a0bf748f/main.sh#L10)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

Does this print the password in the log file?
</blockquote></details>

No, the password is not printed out in the log fie or anywhere. It is read from the file and used at the background.
___
*[`main.sh` line 62 at r2](https://reviewable.io/reviews/moka-guys/archer_api_upload/4#-O7in5sV8iBVAgJaQ6vo:-O7ipfkA7GHhO6KXFofe:bf4c3gp) ([raw file](https://github.com/moka-guys/archer_api_upload/blob/374f78ac49a069f2524b007d6fe894791696b6be/main.sh#L62)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

assuming the proxy command would go here
</blockquote></details>

yes, proxy command has to added in to the curl command here if whitelist is not removed.

**Review by natashapinto — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_api_upload/4)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @wintun12)

**Review by natashapinto — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_api_upload/4#-:-O82T-e10itONR5XWnUa:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @wintun12)

**Pull request merged**
